services:
  # Backend Service - Java Spring Boot
  - type: web
    name: faraj-project-backend
    env: java
    rootDir: backend
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: faraj-project-db
          property: connectionString
      - key: SUPABASE_URL
        value: https://pejuystijjkjxjctieyb.supabase.co
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_ROLE_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: BREVO_SMTP_SERVER
        value: smtp-relay.brevo.com
      - key: BREVO_SMTP_PORT
        value: 587
      - key: BREVO_SMTP_USERNAME
        value: 96f5ae002@smtp-brevo.com
      - key: BREVO_API_KEY
        value: JVfMqU97vcRdFLYr
      - key: BREVO_SENDER_EMAIL
        value: noreply@odvsicilia.it
      - key: BREVO_SENDER_NAME
        value: Faraj Project
      - key: FRONTEND_URL
        value: https://odvsicilia.it

  # Static Frontend Website
  - type: static
    name: faraj-project-frontend
    rootDir: frontend
    buildCommand: echo "No build needed for static site"
    staticPublishPath: .
    envVars:
      - key: SUPABASE_URL
        value: https://pejuystijjkjxjctieyb.supabase.co
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_ROLE_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: BREVO_API_KEY
        value: JVfMqU97vcRdFLYr

databases:
  - name: faraj-project-db
    databaseName: farajproject
    user: farajproject
    